version: '3'

services:
  app:
    image: docker.guidojw.nl/guidojw/update-collaborators:latest
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - /opt/app/node_modules
