name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Add problem matchers
        run: |
          echo '::add-matcher::.github/problem-matchers/tsc.json'

      - name: Build test image
        uses: guidojw/actions/build-docker-image@ec8c080252c6b8903a4431211b78c543609f5f89 # v1.4.6
        with:
          name: app

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Add problem matchers
        run: |
          echo '::add-matcher::.github/problem-matchers/actionlint.json'
          echo '::add-matcher::.github/problem-matchers/eslint-stylish.json'

      - name: Download actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.23

      - name: Load test image
        uses: guidojw/actions/load-docker-image@ec8c080252c6b8903a4431211b78c543609f5f89 # v1.4.6
        with:
          name: app

      - name: Lint
        run: |
          EXIT_STATUS=0
          ./actionlint -ignore 'property "gh_app_private_key" is not defined' -ignore 'SC2153:' \
            -ignore 'property "sha" is not defined in object type {}' || EXIT_STATUS=$?
          docker run app yarn lint || EXIT_STATUS=$?
          exit $EXIT_STATUS
